# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f40ae76bd95794c816112d6a8f4e6be53b2191b7cd841858f120c7bdcb1d39570f333a6fa571ad45f680553906154dfe6d60c77e5bbe4aef9f4c3429d836cf

test:
  secret_key_base: 33b34e6bd98bb1c27be9cc7a88545b5599221bf91e1c89f7bf89acf939e4a766504a49af1a831a0bd68daa662240c1808c6bd5da0ca8e611a2a65422574f1574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
